src/davixxa_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    url(r'^projects/', include("projs.urls", namespace='projs')),
    url(r'', include("static_pages.urls", namespace='static')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^source/', include("gitlab_watcher.urls", namespace='gitlab')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.conf.urls import url
from .views import (
  post_list,
  post_detail,
)

urlpatterns = [

    url(r'^(?P<slug>[\w-]+)/?$', post_detail, name='detail'),
    url(r'^$', post_list, name='list'),

]

src/search/urls.py
from django.conf.urls import url
from .views import (
    search
)

urlpatterns = [
    url(r'^$', search, name='search'),
]

src/static_pages/urls.py
from django.conf.urls import url
from .views import (
    index,
    about,
    redirect_view
)

from .feeds import RSS

urlpatterns = [

    url(r'^$', index, name='index'),
    url(r'about/?', about, name='about'),
    url(r'^rss/?', RSS(), name='rss'),
    url(r'^r/(?P<slug>[\w-]+)/?$', redirect_view, name='redirect')

]

src/search/models.py
from django.db import models

# Create your models here.

src/search/views.py
from django.shortcuts import render
from django.db.models import Q
from django.views.decorators.cache import cache_page
from itertools import chain

from posts.models import Post
from projs.models import Project
from gitlab_watcher.models import GitlabProject
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
@cache_page(60 * 15) # 15min search cache comment this line while developing
def search(request):
    """Render search page

        Search: projects, posts
        keys: title, content, user
    """
    query = request.GET.get("q")

    queryset_posts = Post.objects.all().order_by("-timestamp").filter(draft=0)
    queryset_projs = Project.objects.all().order_by("-timestamp").filter(draft=0)
    queryset_gitlab = GitlabProject.objects.all().order_by("-timestamp")

    if query:
        queryset_posts = queryset_posts.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()

        queryset_projs = queryset_projs.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()

        queryset_gitlab = queryset_gitlab.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()

    queryset = sorted(chain(queryset_posts, queryset_projs, queryset_gitlab),
                      key=lambda instance: instance.timestamp, reverse=True)

    
    paginator = Paginator(queryset, 10)

    page = request.GET.get("page")

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)
        

    

    context = {
        "queryset": results, # limit search results default 10
        "pages" : paginator.num_pages
    }

    return render(request, "search.html", context=context)

src/templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}

{% block content %}

<div class="ui container">
        <div align="center">
                <h1>About me</h1>
        </div>
        <div class="ui message">
            <p>Hi, I'm Davixxa. I'm a {{ age }} year old high school student. Welcome to my website!</p>
            <p>Unless you somehow stumbled upon my website from Google, know me in real life or something along those lines, you probably know me from a few places.</p>
            <p>You might know me from the <a href="http://reddit.com/r/steinsgate">Steins;Gate subreddit</a>, as well as it's <a href="https://discord.gg/YBmZzfA">Discord Server</a>, or you might know me from my <a href="http://youtube.com/Davixxa">YouTube Channel</a>.</p>
            <p>I'm an avid anime-viewer, as well as a large fan of the <ruby><rb>科学</rb> <rt>かがく</rt><rb>アドベンチャーシリーズ</rb><rt>Adventure</rt>/科学ADV</ruby> (Science Adventure/SciADV) franchise. Other things I enjoy are gaming, my main games currently being World of Warcraft and League of Legends. Aside from that, I quite enjoy programming, hence me making this site in the first place.</p>
            <p>My language of choice is Python, but I know a bit of C#, Java, Lua and PHP.</p>
            <p>You can find me on <a href="http://twitter.com/DavixxaYT">Twitter</a>, <a href="http://myanimelist.net/animelist/Davixxa">MyAnimeList</a>, <a href="http://http://curiouscat.me/Davixxa ">CuriousCat</a> as well as YouTube, which I mentioned before.</p>
        </div>



    <div align="center">
        <h1>Attributions</h1>
    </div>
    <div class="ui message">
        <p>Currently, as of writing this (February 10th, 2018) I'm using the following libraries for this website (list extracted from my pip freeze)</p>

        <ul>

            <li>Django</li>
            <li>Django-Markdown</li>
            <li>Gunicorn</li>
            <li>Markdown</li>
            <li>MySQLClient</li>
            <li>Pillow</li>
            <li>python-dateutil</li>
            <li>requests</li>
            <li>And any dependencies each have.</li>

        </ul>
    </div>
</div>

{% endblock %}

src/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'semantic/semantic.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <title>Davixxa.net | {%block title %} 404 Page Not Found{% endblock %}</title>
    <link rel="alternate" type="application/rss+xml" title="Davixxa > Feed" href="{% url 'static:rss' %}">
</head>
<body class="Site">
    <header>
        <div class="ui grid">
            <div class="row">
                <div class="sixteen wide column">
                    <div class="ui stackable inverted top menu">
                        <div class="ui header item">Davixxa</div>
                        <a href="{% url 'static:index' %}" class="item">Home</a>
                        <a href="{% url 'static:about' %}" class="item">About</a>
                        <a href="{% url 'posts:list' %}" class="item">Blog</a>
                        <a href="{% url 'projs:list' %}" class="item">Projects</a>
                        
                    </div>
                </div>
            </div>
        </div>

    </header>


    <br><br>

    <main role="main" class="Site-content">
                {% block content %}
                <h1>404 Not Found</h1>
                <p>We're sorry, but we couldn't find your page.</p>
                {% endblock %}

    </main>


    <br><br>
        
    <footer>
            
                    <div class="ui equal width padded grid">
            
                        <div class="row">
                            <div class="black column">
            
                                <h4>Davixxa - Insert Generic Tagline here</h4>
            
                            </div>
                            <div class="black center aligned column">
                                <a href="{% url 'static:index' %}">Home</a> &bull;
                                <a href="{% url 'static:about' %}">About</a> &bull;
                                <a href="{% url 'posts:list' %}">Blog</a> &bull;
                                <a href="{% url 'projs:list' %}">Projects</a>
                            </div>
                            <div class="black right aligned column">
            
                                Copyright &copy; <span id="year"></span> Davixxa
            
                            </div>
                        </div>
                    </div>
            
                </footer>
            


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            var d = new Date().getFullYear()
            $("#year").html(d)
        })
    </script>
    {% block extra_scripts %}
    {% endblock %}
</body>
</html>

src/templates/gitlab_detail.html
{% extends 'base.html' %}

{% block title %} Commits for {{ project.title }} {% endblock %}

{% block content %}


<div class="ui container">
        <div class="ui grid">
            <div class="ui two wide column"></div>
            <div class="ui twelve wide column">
                <div class="ui message">
                    <span class="ui huge header">Commits for {{ project.title }}</span>
                    <br>
                    <span class="ui sub header">{{project.description}}</span> 
                    <h3><a href="{{project.url}}">Link to the Gitlab Repository</a></h3>
                </div>
            </div>
        </div>
</div>

<br>

{%for commit in commits%}
    <div class="ui container">
        <div class="ui fluid message">
            <span class="ui huge header">Commit by {{ commit.committer_name }} on {{ commit.committed_date }}</span>
            <span class="ui sub header">Commit ID: <a href="{{project.url}}/commit/{{commit.short_id}}">{{commit.short_id}}</a></span>
            <br>
            
        
            <!--<p>{{commit}}</p>-->
            <!--<h2> Commit by {{ commit.committer_name }} on {{ commit.committed_date }} </h2>-->
            <p>{{commit.message |linebreaksbr |safe}}</p>
            <p></p>
        </div>
        <br>
    </div>

{% endfor %}
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}



{% block content %}
            <div class="ui container">

                <div class="ui grid">
                    <div class="row">
                        <div class="sixteen wide column">
                            <div class="ui fluid message">
                                <span class="ui huge header">Davixxa's Spot</span><br>
                                <span class="ui sub header">Ramblings of a lazy weeb tech enthusiast.</span>
                                <br>
                                
                                <form method='GET' action="{% url 'search:search' %}">
                                    <div class="ui icon input">
                                        <input id="search-input" type='text' class="field" name='q' placeholder='Search' value='{{ request.GET.q }}' />
                                        <i class="search icon"></i>
                                    </div>
                                    
                                     <button class="ui grey button" type="submit">Search</button>

                                </form>
                            </div>
                        </div>
                    </div>
                
                    <div class="row">
                        <div class="sixteen wide column">
                            <h2 class="">Recent Posts:</h2>
                            <div class="ui divider"></div>
                        </div>
                    </div>

                
                    <div class="row">

                    <div class="ui three cards">
                    
                        {% for post in query_set %}
                        
                        <div class="ui link fluid card davcard">
                        
                            <div class="image">
                                <img onclick="window.location='{{ post.get_absolute_url }}'" src="{{ post.image }}" alt="">
                            </div>
                            <div class="content">
                                <span class="header"><h3>{{ post.title }}</h3></span>
                                <div class="meta">
                                    <span class="date">{{ post.timestamp }} </span>
                                </div>
                                <div class="extra content">
                                        <a class="author">
                                        <i class="user icon"></i>
                                        {{ post.author }}
                                        </a>
                                    </div>
                                <br>
                                <div class="description"><a href="{{ post.get_absolute_url }}"><h4><i class="angle right icon"></i> Read the post. </h4></a></div>
                                
                            </div>
                        </div>
                        
                        <!--<a href="{% url 'posts:detail' slug=post.slug %}"><h1>{{post.title}}</h1></a>-->
                {% endfor %}
                    </div>
                </div>
            </div>
    
{% endblock %}

src/templates/post_detail.html
{% extends 'base.html' %}


{% block title %} {{ instance.title }} {% endblock %}


{% block content %}
    <div class="article">
        <div class="ui container">
            <div align="center">
                <img src="{{ instance.image }}" alt="" style="width: 60%; max-height: 50rem;" align="center">
            </div>
            <div class="ui message">
                <h1 align="center">{{instance.title}}</h1>
                <div class="body">{{instance.content |safe}}</div>
            </div>
        </div>
    </div>

    <br><br>
{% endblock %}

{% block extra_scripts %}
{% if instance.math %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.css" integrity="sha384-8QOKbPtTFvh/lMY0qPVbXj9hDh+v8US0pD//FcoYFst2lCIf0BmT58+Heqj0IGyx" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.js" integrity="sha384-GR8SEkOO1rBN/jnOcQDFcFmwXAevSLx7/Io9Ps1rkxWp983ZIuUGfxivlF/5f5eJ" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/contrib/auto-render.min.js" integrity="sha384-cXpztMJlr2xFXyDSIfRWYSMVCXZ9HeGXvzyKTYrn03rsMAlOtIQVzjty5ULbaP8L" crossorigin="anonymous"></script>
<script> // katex
renderMathInElement(document.body, {"delimiters": [
    {left: "$$", right: "$$", display: true},
    {left: "$", right: "$", display: false}
]});
</script>
{% endif %}
{% endblock %}

src/templates/post_list.html
{% extends 'base.html' %}

{% block title %} Posts {% endblock %}

{% block content %}

<div class="ui container">
        <div class="ui grid">
    
                <h1>Posts</h1>
    
                <div class="ui two cards">
                    {% for post in posts %}
                
                                    <div class="ui link fluid card davcard"> 
                                        <div class="image">
                                            <img onclick="window.location='{{ post.get_absolute_url }}'" src="{{ post.image }}" alt="">
                                        </div>
                                        <div class="content">
                                            <span class="header"><h3>{{ post.title }}</h3></span>
                                            <div class="meta">
                                                <span class="date">{{ post.timestamp }} </span>
                                            </div>
                                            <div class="extra content">
                                                    <a class="author">
                                                    <i class="user icon"></i>
                                                    {{ post.user.get_username }} 
                                                    </a>
                                                </div>
                                            <br>
                                            <div class="description"><a href="{{ post.get_absolute_url }}"><h4><i class="angle right icon"></i> Read more. </h4></a></div>  
                                        </div>
                                    </div>
                
                
                    {% endfor %}
                </div>
                
                    <div class="row">
                            <div class="six wide column"></div>
                            {% if not posts.has_previous %}
                                <div class="one wide column"> &nbsp; </div>
                            {% endif %}
                
                            <div class="pagination">
                
                                    <span class="step-links">
                            
                                        {% if posts.has_previous %}
                                            <button onclick='location.href="?page={{ posts.previous_page_number }}";' class="ui red button">Previous</button>
                                        {% endif %}
                            
                                        <span class="current">
                                            Page {{ posts.number }} of {{ pages }} 
                                        </span>
                
                                        &nbsp;
                            
                                        {% if posts.has_next %}
                                            <button onclick='location.href="?page={{ posts.next_page_number }}";' class="ui primary button">Next</button>
                                        {% endif %}
                            
                            
                                    </span>
                            
                            
                                </div>
                
                </div>
                
    
        </div>
    </div>



{% endblock %}

src/templates/project_detail.html
{% extends 'base.html' %}

{% block title %} {{ instance.title }} {% endblock %}

{% block content %}
<div class="article">
        <div class="ui container">
            <div align="center">
                <img src="{{ instance.image }}" alt="" style="width: 60%; max-height: 50rem;" align="center">
            </div>
            <div class="ui message">
                <h1>{{instance.title}}</h1>
                <div class="body">{{instance.content |safe}}</div>
                <div class="html">{{ instance.custom_html | safe }}</div>
            </div>
        </div>
    </div>

    <br><br>
{% endblock %}

src/templates/project_list.html
{% extends 'base.html' %}

{% block title %} Projects {% endblock %}

{% block content %}
<div class="ui container">
    <div class="ui grid">

            <h1>Projects</h1>

            <div class="ui two cards">
                {% for project in projects %}
            
                                <div class="ui link fluid card davcard"> 
                                    <div class="image">
                                        <img onclick="window.location='{{ project.get_absolute_url }}'" src="{{ project.image }}" alt="">
                                    </div>
                                    <div class="content">
                                        <span class="header"><h3>{{ project.title }}</h3></span>
                                        <div class="meta">
                                            <span class="date">{{ project.timestamp }} </span>
                                        </div>
                                        <div class="extra content">
                                                <a class="author">
                                                <i class="user icon"></i>
                                                {{ project.user.get_username }} 
                                                </a>
                                            </div>
                                        <br>
                                        <div class="description"><a href="{{ project.get_absolute_url }}"><h4><i class="angle right icon"></i> Read more. </h4></a></div>  
                                    </div>
                                </div>
            
            
                {% endfor %}
            </div>
            
                <div class="row">
                        <div class="six wide column"></div>
                        {% if not projects.has_previous %}
                            <div class="one wide column"> &nbsp; </div>
                        {% endif %}
            
                        <div class="pagination">
            
                                <span class="step-links">
                        
                                    {% if projects.has_previous %}
                                        <button onclick='location.href="?page={{ projects.previous_page_number }}";' class="ui red button">Previous</button>
                                    {% endif %}
                        
                                    <span class="current">
                                        Page {{ projects.number }} of {{ pages }} 
                                    </span>
            
                                    &nbsp;
                        
                                    {% if projects.has_next %}
                                        <button onclick='location.href="?page={{ projects.next_page_number }}";' class="ui primary button">Next</button>
                                    {% endif %}
                        
                        
                                </span>
                        
                        
                            </div>
            
            </div>
            

    </div>
</div>
{% endblock %}

src/templates/search.html
{% extends 'base.html' %}

{% block title %} Search {{ request.GET.q }} {% endblock %}

{% block content %}


<div class="ui container">
    <div class="ui grid">
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui fluid message">
                    <div class="ui huge header">Search:</div><br>
                    <form method='GET' action="{% url 'search:search' %}">
                        <div class="ui icon input">
                            <input id="search-input" type='text' class="field" name='q' placeholder='Search' value='{{ request.GET.q }}' />
                            <i class="search icon"></i>
                        </div>
                        <button class="ui grey button" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>

        {% if request.GET.q %}
        <h1>Search Results:</h1>
        {% endif %}
        <br>


        <div class="row">
            <div class="ui two cards">
                {% for post in queryset %}
                    <div class="ui link fluid card davcard"> 
                        <div class="image">
                            <img onclick="window.location='{{ post.get_absolute_url }}'" src="{{ post.image }}" alt="">
                        </div>
                        <div class="content">
                            <span class="header"><h3>{{ post.title }}</h3></span>
                            <div class="meta">
                                <span class="date">{{ post.timestamp }} </span>
                            </div>
                            <div class="extra content">
                                    <a class="author">
                                    <i class="user icon"></i>
                                    {{ post.user.get_username }} 
                                    </a>
                                </div>
                            <br>
                            <div class="description"><a href="{{ post.get_absolute_url }}"><h4><i class="angle right icon"></i> Read more. </h4></a></div>  
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>

            <div class="row">
                    <div class="six wide column"></div>
                    {% if not queryset.has_previous %}
                        <div class="one wide column"> &nbsp; </div>
                    {% endif %}

                    <div class="pagination">

                            <span class="step-links">
                    
                                {% if queryset.has_previous %}
                                    <button onclick='location.href="?q={{request.GET.q}}&page={{ queryset.previous_page_number }}";' class="ui red button">Previous</button>
                                {% endif %}
                    
                                <span class="current">
                                    Page {{ queryset.number }} of {{ pages }} 
                                </span>

                                &nbsp;
                    
                                {% if queryset.has_next %}
                                    <button onclick='location.href="?q={{request.GET.q}}&page={{ queryset.next_page_number }}";' class="ui primary button">Next</button>
                                {% endif %}
                    
                    
                            </span>
                    
                    
                        </div>

        </div>

    </div>
</div>
{% endblock %}